name = "animasters"
type = "webpack"
route = ''
zone_id = ''
account_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2023-04-08"
webpack_config = "webpack.config.js"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
name = "animasters"
